# Titre du formulaire de contact
title:              "<?php _e( 'Formulaire de contact', 'tify' );?>"

# Affichage de l'interface d'administration des options
tify_options:       true

# Liaison du formulaire à une page
## Activation de la fonctionnalité
hookpage:           true
## Affichage du contenu de la page ( 'before' | 'after' | false )
content:            'before'

# Configuration du formulaire
form:
  container_class:  'tify_contact_form'
  before:           ''
  after:            ''
  fields:
    -
      slug:         'lastname'
      label:        "<?php _e( 'Nom', 'tify' );?>"
      placeholder:  "<?php _e( 'Renseignez votre nom', 'tify' );?>"
      type:         'input'
      required:     true
    -
      slug:         'firstname'
      label:        "<?php _e( 'Prénom', 'tify' );?>"
      placeholder:  "<?php _e( 'Renseignez votre prénom', 'tify' );?>"
      type:         'input'
      required:     true
    -
      slug:         'email'
      label:        "<?php _e( 'Adresse mail', 'tify' );?>"
      placeholder:  "<?php _e( 'Indiquez votre adresse email', 'tify' );?>"
      type:         'input'
      integrity_cb: 'is_email'
      required:     true     
    -
      slug:         'subject'
      label:        "<?php _e( 'Sujet du message', 'tify' );?>"
      placeholder:  "<?php _e( 'Sujet de votre message', 'tify' );?>"
      type:         'input'
      required:     true 
    -
      slug:         'message'
      label:        "<?php _e( 'Message', 'tify' );?>"
      placeholder:  "<?php _e( 'Votre message', 'tify' );?>"
      type:         'textarea'
      required:     true 
    -
      slug:         'message'
      label:        "<?php _e( 'Message', 'tify' );?>"
      placeholder:  "<?php _e( 'Votre message', 'tify' );?>"
      type:         'textarea'
      required:     true
    -
      slug:         'captcha'
      label:        "<?php _e( 'Code de sécurité', 'tify' );?>"
      placeholder:  "<?php _e( 'Code de sécurité', 'tify' );?>"
      type:         'simple-captcha-image' 
  options:
  buttons:
  add-ons: