# Id HTML du conteneur
id:           ''

# Classe HTML du conteneur
class:        ''

# Contenu HTML affiché avant le fil d'Ariane 
before:       ''

# Contenu HTML affiché après le fil d'Ariane
after:        ''