# Position
pos:                'left'

# Etat initial : closed (default) | opened 
initial:            'closed'

# Largeur
width:              300px

# Profondeur de champs 
z-index:            99990

# Responsive
min-width:          991px

# Animation à l'ouverture et la fermeture
animated:           true

# Bouton de bascule : bool or string true | false | ex : <span>X</span>
toggle:             true

# Mise en file automatique des scripts (dans tous les contextes)
enqueue_scripts:    true  

# Elements de menu
nodes: