defaults:
  posts_per_section:  4
  show_all:           true
  fields:             [ 'post_title', 'post_excerpt', 'post_content' ]
sections:
  # Exemple :
  
  #@ Identifiant de la section
  #test:
    #@ type de poste de la section dans la page de résultat de recherche
    #post_type:     'page'
    
    #@ Champs de recherche
    #fields:     
    
    #  0:        'post_title'
    
    #  1:        'post_content'
    
    #@ Champs de recherche par clef de métadonnée
    #  postmeta: ['data', '_reference']

#@ Activation de la recherche par mot-clef    
#tags:           ['page']    