# Personnalisation de l'entrée de menu logo de l'adminbar
admin_bar_menu_logo :

# Nettoyage des entrées de menu de la barre d'administration
remove_admin_bar_menu:
# ex : [ 'wp_logo', 'about', 'wporg', 'documentation', 'support-forums', 'feedback', 'site-name', 'view-site', 'updates', 'comments', 'new-content', 'my-account', 'disable_post', 'disable_post_category', 'disable_post_tag', 'disable_comment' ]

#-------------------------------------------------------------------------------------------------------
# Personnalisation du texte  du pied de page de l'interface d'administration
admin_footer_text:

#-------------------------------------------------------------------------------------------------------
# Nettoyage des entrées de menu de l'interface d'administration
remove_menu:
# ex: [ 'dashboard', 'posts', 'media', 'pages', 'comments', 'appearence', 'plugins', 'users', 'tools', 'settings' ]
# alt: [ 'index.php', 'edit.php', 'upload.php', 'edit.php?post_type=page', 'edit-comments.php', 'themes.php', 'plugins.php', 'users.php', 'tools.php', 'options-general.php' ]

#------------------------------------------------------------------------------------------------------- 
# Nettoyage des entrées de menu de l'interface d'administration
unregister_widget:
# ex: [ 'pages', 'calendar', 'archives', 'links', 'meta', 'search', 'text', 'categories', 'recent posts', 'recent comments', 'rss', 'tag cloud', 'nav menu' ]
 
#-------------------------------------------------------------------------------------------------------  
# Suppression des boîtes de saisie du tableau de bord
remove_dashboard_meta_box:
# ex: [ 'right_now', 'recent_comments', 'incoming_links', 'plugins', 'quick_press', 'recent_drafts', 'activity', 'primary', 'secondary' ]
# alt: { right_now: 'normal', recent_comments: 'normal', incoming_links: 'normal', plugins: 'normal', quick_press: 'normal', recent_drafts: 'normal', activity: 'normal', primary: 'normal', 'secondary': 'normal' }

#-------------------------------------------------------------------------------------------------------  
# Suppression de support  
## Suppression de support des propriétés d'articles
remove_support_post:
# ex: [ 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'trackbacks', 'custom-fields', 'comments', 'revisions', 'post-formats' ]

## Suppression de support des propriétés de page
remove_support_page:
# ex: [ 'title', 'editor', 'author', 'thumbnail', 'page-attributes', 'custom-fields', 'comments', 'revisions' ]

## Suppression de support des propriétés d'un type de post personnalisé (%%custom_post_type%%)
#remove_support_%%custom_post_type%% : [ 'title', 'editor' ]

#-------------------------------------------------------------------------------------------------------
# Suppression des boîtes de saisie
## Suppression des boîtes de saisie du tableau de bord
remove_dashboard_meta_box:
# ex: [ 'recent_comments', 'incoming_links', 'plugins', 'recent_drafts', 'activity', 'primary', 'secondary' ]

## Suppression des boîtes de saisie des articles
remove_meta_box_post:
# ex: [ 'authordiv', 'categorydiv', 'commentstatusdiv', 'commentsdiv', 'formatdiv', 'postcustom', 'postexcerpt', 'postimagediv', 'revisionsdiv', 'slugdiv', 'submitdiv', 'tagsdiv-post_tag', 'trackbacksdiv' ]
# alt: { authordiv: 'normal', categorydiv: 'side', commentstatusdiv: 'normal', commentsdiv: 'normal', formatdiv: 'normal', postcustom: 'normal', postexcerpt: 'normal', postimagediv: 'normal', revisionsdiv: 'normal', slugdiv: 'normal', submitdiv: 'side', tagsdiv-post_tag: 'side', trackbacksdiv: 'normal' }

## Suppression des boîtes de saisie des pages
remove_meta_box_page:
# ex: [ 'authordiv', 'commentstatusdiv', 'commentsdiv', 'pageparentdiv', 'postcustom', 'postimagediv', 'revisionsdiv', 'slugdiv', 'submitdiv' ]
# alt: { authordiv: 'normal', commentstatusdiv: 'normal', commentsdiv: 'normal', pageparentdiv: 'side', postcustom: 'normal', postimagediv: 'normal', revisionsdiv: 'normal', slugdiv: 'normal', submitdiv: 'side' }

## Suppression des boîtes de saisie d'un type de post personnalisé (%%custom_post_type%%)
# remove_meta_box_%%custom_post_type%% :
# ex: [ 'authordiv', 'commentstatusdiv', 'commentsdiv', 'pageparentdiv', 'postcustom', 'postimagediv', 'revisionsdiv', 'slugdiv', 'submitdiv' ]
# alt: { authordiv: 'normal', commentstatusdiv: 'normal', commentsdiv: 'normal', pageparentdiv: 'side', postcustom: 'normal', postimagediv: 'normal', revisionsdiv: 'normal', slugdiv: 'normal', submitdiv: 'side' }

#-------------------------------------------------------------------------------------------------------
# Désactivation des interfaces commentaire
disable_comment:          false

#-------------------------------------------------------------------------------------------------------
# Désactivation des catégories d'articles
disable_post_category:    false

#-------------------------------------------------------------------------------------------------------
# Désactivation des etiquettes (mot-clefs) d'articles
disable_post_tag:         false