# Titre du formulaire de contact
title:              "<?php _e( 'Formulaire de contact', 'tify' );?>"

# Affichage de l'interface d'administration des options
# bool || [ 'hookpage', 'confirmation', 'notification' ]
admin:              true

# Liaison du formulaire à une page
## Activation de la fonctionnalité
hookpage:           true
## Affichage du contenu de la page ( 'before' | 'after' | 'hide' | true | false )
## 'before' : Affiche le contenu du post avant le formulaire
## 'after'  : Affiche le contenu du post après le formulaire
## 'hide'   : Masque le contenu du post
## 'only'   : Affiche seulement le contenu du post, le formulaire est masqué et doit être appelé manuellement
## false    : Masque à la fois le contenu du post et le formulaire
content:            'before'

# Configuration du formulaire
form:
  container_class:  'tiFySetContactForm'
  before:           ''
  after:            ''
  fields:
    -
      slug:         'lastname'
      label:        "<?php _e( 'Nom', 'tify' );?>"
      placeholder:  "<?php _e( 'Renseignez votre nom', 'tify' );?>"
      type:         'input'
      required:     true
      add-ons:
        mailer:
          show:         true
    -
      slug:         'firstname'
      label:        "<?php _e( 'Prénom', 'tify' );?>"
      placeholder:  "<?php _e( 'Renseignez votre prénom', 'tify' );?>"
      type:         'input'
      required:     true
      add-ons:
        mailer:
          show:         true
    -
      slug:         'email'
      label:        "<?php _e( 'Adresse mail', 'tify' );?>"
      placeholder:  "<?php _e( 'Indiquez votre adresse email', 'tify' );?>"
      type:         'input'
      integrity_cb: 'is_email'
      required:     true
      add-ons:
        mailer:
          show:         true     
    -
      slug:         'subject'
      label:        "<?php _e( 'Sujet du message', 'tify' );?>"
      placeholder:  "<?php _e( 'Sujet de votre message', 'tify' );?>"
      type:         'input'
      required:     true
      add-ons:
        mailer:
          show:         true 
    -
      slug:         'message'
      label:        "<?php _e( 'Message', 'tify' );?>"
      placeholder:  "<?php _e( 'Votre message', 'tify' );?>"
      type:         'textarea'
      required:     true
      add-ons:
        mailer:
          show:         true
    -
      slug:         'captcha'
      label:        "<?php _e( 'Code de sécurité', 'tify' );?>"
      placeholder:  "<?php _e( 'Code de sécurité', 'tify' );?>"
      type:         'simple-captcha-image'
       
  options:
  buttons:
  add-ons: