posts :
  Db:
    install:        false
    col_prefix:     'post_'
    meta:           'post'
    columns:
      ID:
        type:           'BIGINT'
        size:           20
        unsigned:       true
        auto_increment: true
        prefix:         false

      author:
        type:           'BIGINT'
        size:           20
        unsigned:       true
        default:        0

      date:
        type:           'DATETIME'
        default:        '0000-00-00 00:00:00'

      date_gmt:
        type:           'DATETIME'
        default:        '0000-00-00 00:00:00'

      content:
        type:           'LONGTEXT'

      title:
        type:           'TEXT'

      excerpt:
        type:           'TEXT'

      status:
        type:           'VARCHAR'
        size:           20
        default:        'publish'

      comment_status:
        type:           'VARCHAR'
        size:           20
        default:        'open'
        prefix:         false

      ping_status:
        type:           'VARCHAR'
        size:           20
        default:        'open'
        prefix:         false

      password:
        type:           'VARCHAR'
        size:           20
        default:        ''
        
      name:
        type:           'VARCHAR'
        size:           200
        default:        ''
        
      to_ping:
        type:           'TEXT'
        prefix:         false
        
      pinged:
        type:           'TEXT'
        prefix:         false
        
      modified:
        type:           'DATETIME'
        default:        '0000-00-00 00:00:00'
        
      modified_gmt:
        type:           'DATETIME'
        default:        '0000-00-00 00:00:00'
        
      content_filtered:
        type:           'LONGTEXT'
        
      parent:
        type:           'BIGINT'
        size:           20
        unsigned:       true
        default:        0
        
      guid:
        type:           'VARCHAR'
        size:           255
        default:        '' 
        prefix:         false
        
      menu_order:
        type:           'INT'
        size:           11
        default:        0
        prefix:         false
        
      type:
        type:           'VARCHAR'
        size:           20
        default:        'post'
        
      mime_type:
        type:           'VARCHAR'
        size:           100
        default:        ''
        
      comment_count:
        type:           'BIGINT'
        size:           20
        default:        0
        prefix:         false

    search:
      content
      title
users:
  Db:
    install:        false
    col_prefix:     'user_'
    meta:           'user'
    columns:
      ID:
        type:           'BIGINT'
        size:           20
        unsigned:       true
        auto_increment: true
        prefix:         false
        
      login:
        type:           'VARCHAR'
        size:           60
        default:        ''
     
      pass:
        type:           'VARCHAR'
        size:           255
        default:        ''
      
      nicename:
        type:           'VARCHAR'
        size:           50
        default:        ''
        
      email:
        type:           'VARCHAR'
        size:           100
        default:        ''
          
      url:
        type:           'VARCHAR'
        size:           100
        default:        ''
         
      registered:
        type:           'DATETIME'
        default:        '0000-00-00 00:00:00'      
      
      activation_key:
        type:           'VARCHAR'
        size:           255
        default:        ''
        
      status:
        type:           'INT'
        size:           11
        default:        0
         
      display_name:
        type:           'VARCHAR'
        size:           250
        prefix:         false
        default:        ''
    
      spam:
        type:           'TINYINT'
        size:           2
        prefix:         false
        default:        0
      
      deleted:
        type:           'TINYINT'
        size:           2
        prefix:         false
        default:        0 